apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component-f5pp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-rhtap-devfile-multi-component-f5pp
    app.kubernetes.io/part-of: mc-two-scenarios
  name: devfile-sample-python-basic-rhtap-devfile-multi-component-f5pp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component-f5pp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component-f5pp
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qypj-tenant/mc-two-scenarios/devfile-sample-python-basic-rhtap-devfile-multi-component-f5pp@sha256:967997d82cb5634b5d056c5e7fe00067cb567fb1249b05782e56e835c562f7e4
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
